In [26]:
## Import Ticker class from yahooquery library 
# To access data from yahooquery, an argument (Company ticker symbol) is passed to the Ticker class 

from yahooquery import Ticker
import pandas as pd

In [27]:
## Create instance of Ticker class (Company ticker symbol)

WES_ASX = Ticker(['WES.AX'])

In [28]:
# Select the Income Statement from the Ticker class, this will return a DataFrame

cashFlowStatement = WES_ASX.cash_flow().reset_index()

# Additionally, the Balance Sheet & Income Statement will be selected, as some of the columns are required for the calculations

balanceSheet = WES_ASX.balance_sheet().reset_index()
incomeStatement = WES_ASX.income_statement().reset_index()

# Print top 5 results for the cashFlowStatement object

cashFlowStatement.head()

,symbol,asOfDate,periodType,currencyCode,BeginningCashPosition,CapitalExpenditure,CashDividendsPaid,CashFlowFromContinuingFinancingActivities,CashFlowFromContinuingInvestingActivities,CashFlowsfromusedinOperatingActivitiesDirect,...,PaymentstoSuppliersforGoodsandServices,PurchaseOfBusiness,PurchaseOfInvestment,PurchaseOfPPE,ReceiptsfromCustomers,RepaymentOfDebt,SaleOfBusiness,SaleOfInvestment,SaleOfPPE,TaxesRefundPaidDirect
0,WES.AX,2019-06-30,12M,AUD,6.830000e+08,-1.356000e+09,-3.628000e+09,-2.851000e+09,245000000.0,2.718000e+09,...,-4.489200e+10,-17000000.0,NaN,-1.356000e+09,4.877000e+10,-1.164000e+09,858000000.0,2.310000e+08,529000000.0,-1.082000e+09
1,WES.AX,2019-06-30,TTM,AUD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,858000000.0,NaN,NaN,NaN
2,WES.AX,2020-06-30,12M,AUD,7.950000e+08,-8.670000e+08,-1.734000e+09,-3.070000e+09,642000000.0,4.546000e+09,...,-2.872500e+10,-988000000.0,NaN,-8.670000e+08,3.419700e+10,-3.810000e+08,NaN,2.198000e+09,299000000.0,-7.270000e+08
3,WES.AX,2020-06-30,TTM,AUD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.198000e+09,NaN,NaN
4,WES.AX,2021-06-30,12M,AUD,2.913000e+09,-8.960000e+08,-2.074000e+09,-2.631000e+09,-642000000.0,3.383000e+09,...,-3.277300e+10,-2000000.0,-13000000.0,-8.960000e+08,3.740300e+10,-5.710000e+08,5000000.0,NaN,264000000.0,-1.015000e+09